title: <p align="center"> Harshul Agarwal </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harshul-agarwal-1b2313144/">LinkedIn</a> |
  <a href="https://github.com/Harshulagarwal">GitHub</a>



theme: jekyll-theme-minimal
