title: <p align="center"> Harshul Agarwal </p>

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/harshul-agarwal-1b2313144/">LinkedIn</a> |
  <a href="https://github.com/Harshulagarwal">GitHub</a>
  <br>   
  I'm working in Samsung Research Institute Noida since past 1 year.
  <br>
  </p>



theme: jekyll-theme-minimal
